// @ts-nocheck
export const AUTH_TEXT = {
  ko: {
    brand: "Dayflow",
    tagline: "하루를 가볍게, 한 달을 단단하게",
    // login
    loginTitle: "다시 만나서 반가워요",
    loginSub: "이메일로 로그인하거나 구글 계정을 연결하세요",
    email: "이메일",
    password: "비밀번호",
    forgot: "비밀번호를 잊으셨나요?",
    signin: "로그인",
    google: "구글로 계속하기",
    or: "또는",
    noAccount: "아직 계정이 없으신가요?",
    signup: "가입하기",
    // signup
    signupTitle: "계정 만들기",
    signupSub: "30초면 충분해요. 이름과 이메일만 있으면 시작합니다",
    name: "이름",
    confirm: "비밀번호 확인",
    agree1: "이용약관 및 개인정보처리방침에 동의합니다",
    agree2: "마케팅 정보 수신에 동의합니다 (선택)",
    create: "계정 만들기",
    haveAccount: "이미 계정이 있으신가요?",
    login: "로그인",
    // pwd strength
    pwdWeak: "약함",
    pwdMid: "보통",
    pwdStrong: "강력함",
    // onboarding
    welcome: "환영합니다,",
    obStep: "단계",
    skip: "건너뛰기",
    next: "다음",
    back: "이전",
    done: "시작하기",
    // step 1
    ob1Title: "어떻게 쓸 계획이세요?",
    ob1Sub: "주된 용도를 알려주시면 화면을 맞춰드려요",
    purpose1: "가계부 위주",
    purpose1d: "지출 기록과 예산 관리",
    purpose2: "일정 위주",
    purpose2d: "캘린더와 할 일",
    purpose3: "둘 다 통합",
    purpose3d: "돈과 시간을 한곳에서",
    // step 2
    ob2Title: "월급일을 알려주세요",
    ob2Sub: "이 날을 기준으로 한 달의 예산을 계산해드려요",
    salaryDay: "매월 ",
    day: "일",
    skipDay: "월급이 일정하지 않아요",
    // step 3
    ob3Title: "관심 카테고리를 골라주세요",
    ob3Sub: "자주 쓰는 카테고리만 보여드릴게요. 나중에 바꿀 수 있어요",
    cats: [
      "식비",
      "교통",
      "카페",
      "쇼핑",
      "구독",
      "운동",
      "취미",
      "여행",
      "선물",
      "공과금",
      "병원",
      "기타",
    ],
    // step 4
    ob4Title: "준비됐어요!",
    ob4Sub: "Dayflow로 첫 한 달을 더 가볍게 보내보세요",
    feature1: "가계부와 캘린더를 한 화면에서",
    feature2: "영수증 사진으로 자동 입력",
    feature3: "월급일 기준 스마트 예산",
    // forgot password
    fpTitle: "비밀번호 찾기",
    fpSub: "가입한 이메일을 입력해주세요. 재설정 링크를 보내드릴게요",
    fpSend: "재설정 링크 보내기",
    fpSentTitle: "메일을 보냈어요",
    fpSentSub:
      "받은 편지함에서 이메일을 확인하고 링크를 눌러 비밀번호를 다시 만들어주세요",
    fpResend: "다시 보내기",
    fpCheckSpam: "메일이 안 보이면 스팸함을 확인해주세요",
    fpOpenMail: "메일 앱 열기",
    fpResetTitle: "새 비밀번호 만들기",
    fpResetSub: "8자 이상, 영문과 숫자를 섞어주세요",
    fpNewPwd: "새 비밀번호",
    fpNewPwd2: "비밀번호 확인",
    fpReset: "비밀번호 변경",
    fpResetDone: "변경 완료",
    fpResetDoneSub: "새 비밀번호로 로그인할 수 있어요",
    fpBackToLogin: "로그인으로 돌아가기",
    fpStep: "단계",
    fpEmailNotMatch: "비밀번호가 일치하지 않아요",
    fpSecurityTip: "보안을 위해 1시간 안에 변경해주세요",
  },
  en: {
    brand: "Dayflow",
    tagline: "Lighten your day, strengthen your month",
    loginTitle: "Welcome back",
    loginSub: "Sign in with email or continue with Google",
    email: "Email",
    password: "Password",
    forgot: "Forgot password?",
    signin: "Sign in",
    google: "Continue with Google",
    or: "or",
    noAccount: "Don't have an account?",
    signup: "Sign up",
    signupTitle: "Create your account",
    signupSub: "Takes 30 seconds. Just your name and email to start",
    name: "Name",
    confirm: "Confirm password",
    agree1: "I agree to the Terms and Privacy Policy",
    agree2: "Send me product updates (optional)",
    create: "Create account",
    haveAccount: "Already have an account?",
    login: "Sign in",
    pwdWeak: "Weak",
    pwdMid: "OK",
    pwdStrong: "Strong",
    welcome: "Welcome,",
    obStep: "Step",
    skip: "Skip",
    next: "Continue",
    back: "Back",
    done: "Let's go",
    ob1Title: "How will you use it?",
    ob1Sub: "We'll tailor the experience to your main use",
    purpose1: "Mainly money",
    purpose1d: "Track expenses & budget",
    purpose2: "Mainly time",
    purpose2d: "Calendar & to-dos",
    purpose3: "Both, together",
    purpose3d: "Money & time, one place",
    ob2Title: "When do you get paid?",
    ob2Sub: "Your month resets on this day",
    salaryDay: "Day ",
    day: "",
    skipDay: "Pay isn't regular",
    ob3Title: "Pick categories you use",
    ob3Sub: "We'll surface these first. Change anytime",
    cats: [
      "Food",
      "Transit",
      "Café",
      "Shopping",
      "Subscriptions",
      "Fitness",
      "Hobbies",
      "Travel",
      "Gifts",
      "Bills",
      "Health",
      "Other",
    ],
    ob4Title: "All set!",
    ob4Sub: "Make your next month lighter with Dayflow",
    feature1: "Money and time in one view",
    feature2: "Snap a receipt to log it",
    feature3: "Smart budgets pegged to payday",
    fpTitle: "Forgot password?",
    fpSub: "Enter your email and we'll send a reset link",
    fpSend: "Send reset link",
    fpSentTitle: "Check your inbox",
    fpSentSub:
      "We sent a link to reset your password. Tap it from your email to continue",
    fpResend: "Resend email",
    fpCheckSpam: "Don't see it? Check your spam folder",
    fpOpenMail: "Open mail app",
    fpResetTitle: "Set a new password",
    fpResetSub: "At least 8 characters with letters and numbers",
    fpNewPwd: "New password",
    fpNewPwd2: "Confirm password",
    fpReset: "Update password",
    fpResetDone: "Password updated",
    fpResetDoneSub: "Sign in with your new password",
    fpBackToLogin: "Back to sign in",
    fpStep: "Step",
    fpEmailNotMatch: "Passwords don't match",
    fpSecurityTip: "For security, complete this within 1 hour",
  },
};
